image: docker:20.10.17

services:
  - docker:20.10.17-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  
before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

.build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:${TAG} || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:${TAG} --tag $CI_REGISTRY_IMAGE:${TAG} --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:${TAG}
  tags:
    - dind

build:
  extends: .build
  variables:
    TAG: 20221029
